### ISSUE TITLE
VirusTotal flags AutoPackOpener.exe as potentially malicious 

### ISSUE THREAD

**Issue by remd** [mleonardblair/TCGCardShop-Pack-Opener#1]
https://www.virustotal.com/gui/file/22b77c3f05cea9cc5bc416a91f2f6f5a3eeaee8c950932249a570297d682b868

> 3/71 security vendors flagged this file as malicious.

```
PS E:\projects\public\TCGCardShop-Pack-Opener> git rev-parse HEAD
7a160d79be871f3c22959b0e89deb27a4ba592f4
PS E:\projects\public\TCGCardShop-Pack-Opener> Get-FileHash .\AutoPackOpener.exe

Algorithm       Hash                                                                   Path
---------       ----                                                                   ----
SHA256          22B77C3F05CEA9CC5BC416A91F2F6F5A3EEAEE8C950932249A570297D682B868       E:\projects\public\TCGCardSho..
```

I'm guessing this is likely a false positive and the uncompiled AHK script is enough for me.

**Comment by mleonardblair** [comment]
Hey, there! Thanks for letting me know about this, I'd not have known otherwise. 

If that's the case, I recommend obtaining autohotkeyv2 and running the autohotkey v2 uncompiled script directly from it. I chose to provide it so there is another option, you can check the code in the script if you're able to read it, in any text editor, or otherwise if you want a quick confirmation with chatgpt you can paste it there, that works as well. 

I assure you it is a false positive, however, from one netizen to another, do you have any insights on the compiling process to avoiding having this issue pop up? if I made some mistake I'd like to know!

This is the first times I've compiled a script into an EXE!

**Comment by remd** [comment]
Unfortunately I do not have any insights to offer on why it was flagged.

3/71 vendors is a very low number, and reputable AV companies on the list pass the file (e.g. Avast, Crowdstrike, ESET-NOD32, Kaspersky). When I said I was unwilling to run the EXE it was because the uncompiled AHK script is enough for me, I'm sorry, I should have been more clear in my original post. I will edit it to make it more clear.

FWIW you're not the only one who experiences this: https://www.google.com/search?q=autohotkey+v2+compiling+virustotal

Thanks for your work and sharing the script with the open-source community. I'll leave it up to you whether you want to close this issue or not.

**Comment by mleonardblair** [comment]
I see then thats fine, thanks for clarifying.

I appreciate the kind words, however this wasn't that much effort to make, i'm just happy to have something that is of use. That said, I'm seeing now that from the youtube comments, appears are still a kink reported involving the core function for larger hand sizes, so for now, I'll leave this open, and if someone has something to contribute to the braintrust on this topic I'd be happy if they do so.

**Comment by mleonardblair** [comment]
Resolved closed
